#!/bin/sh
# odoo-create-module - https://github.com/miikanissi/create-odoo-module
# by Miika Nissi - https://miikanissi.com - https://github.com/miikanissi
# Part of odoo-create-module. See LICENSE file for full copyright and licensing details.

# Module defaults
export MODULE_NAME="module"
export NAME="Module"
export CATEGORY=""
export SUMMARY=""
export DESCRIPTION=""
export VERSION="1.0"
export WEBSITE=""
export AUTHOR=""
export LICENSE="LGPL-3"
export APPLICATION=False
export INSTALLABLE=True
export DEPENDS=""
